version: '3.8'

services:
  backend:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - bookamore-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookamore-db:5432/bookamore-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ../backend:/usr/bookamore-backend
      - ~/.m2:/root/.m2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bookamore-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookamore-db
    networks:
      - app-network

  frontend:
    tty: true
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Для корректной работы hot reload в Docker
    #volumes:
    #  - ../frontend:/app 
    #  - /app/node_modules  # Исключаем node_modules из монтирования
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge