version: '3.8'

services:
  backend:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ../backend:/app
      - ~/.m2:/root/.m2  # Кэш Maven для ускорения сборки
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Для корректной работы hot reload в Docker
    volumes:
      - ../frontend:/app
      - /app/node_modules  # Исключаем node_modules из монтирования
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge