### GET for smoke-test
GET http://localhost:8080/api/v1/hello

###  POST for sign up
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "Password1"
}


