server:
  port: 8080

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
    contexts: ${spring.profiles.active}

management:
  endpoints:
    web:
      exposure:
        include: env,health,info
file:
  hash-algorithm: SHA-256
  upload-dir: /app/uploads # dev
  sub-dirs-perms: 775 # Octal POSIX permissions for upload subdirectories
