spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never

file:
  hash-algorithm: SHA-256
  upload-dir: /app/uploads
  sub-dirs-perms: 775 # Octal POSIX permissions for upload subdirectories
