server:
  port: 8080

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    web:
      exposure:
        include: env,health,info

file:
  hash-algorithm: SHA-256
  # Required for local deployment
  # TODO: Move the upload directory configuration to profile-specific files
  upload-dir: ./src/main/resources/uploads
  # Octal POSIX permissions for upload subdirectories
  sub-dirs-perms: 775