changeLogFile=src/main/resources/db/changelog/master.yaml
outputChangeLogFile=src/main/resources/db/changelog/changelog.sql 
diffChangeLogFile=src/main/resources/db/changelog/diff.sql

url=jdbc:postgresql://localhost:5432/bookamore
username=postgres
password=postgres
driver=org.postgresql.Driver

referenceUrl=hibernate:spring:com.bookamore.backend.entity?dialect=org.hibernate.dialect.PostgreSQLDialect